name: Create documentation ticket

on:
  pull_request_target:
    branches:
      - main
    types:
      - closed

jobs:
  create-docs-ticket:
    if: github.event.pull_request.merged && contains(github.event.pull_request.labels.*.name, 'DocumentationNeeded')
    runs-on: ubuntu-22.04
    steps:
      - name: Create Issue
        id: create-issue
        uses: actions/github-script@v6
        with:
          script: |
            const script = require('.github/workflows/docs-issue.js');
            await script({github, context});
